spring.application.name=s3-reverse-proxy
server.port=8000

# Base URL to S3 bucket outputs (Defaults to environment variables)
s3.bucket.name=${S3_BUCKET_NAME:vercel-clone-outputs}
aws.region=${AWS_REGION:ap-south-1}
s3.base.url=${S3_BASE_URL:https://${s3.bucket.name}.s3.${aws.region}.amazonaws.com/__outputs}
