spring.application.name=build-server

# AWS Configuration (Supports AWS ECS Task IAM Roles or Environment Credentials)
aws.region=${AWS_REGION:ap-south-1}
aws.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
aws.s3.endpoint=${AWS_ENDPOINT:}
s3.bucket.name=${S3_BUCKET_NAME:vercel-clone-outputs}

# Workspace
build.workspace.dir=${BUILD_WORKSPACE_DIR:/app/output}
