spring.application.name=build-server

# Optional import for private local credentials (Ignored by .gitignore)
spring.config.import=optional:classpath:application-secret.properties,optional:file:./application-secret.properties,optional:file:../application-secret.properties

# AWS Configuration (Reads from Environment Variables, application-secret.properties, or IAM Roles)
aws.region=${AWS_REGION:ap-south-1}
aws.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
aws.s3.endpoint=${AWS_ENDPOINT:}
s3.bucket.name=${S3_BUCKET_NAME:}

# Redis Configuration for real-time logs
redis.url=${REDIS_URL:redis://localhost:6379}

# Workspace
build.workspace.dir=${BUILD_WORKSPACE_DIR:/app/output}
